# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsimple < Formula
  desc "DNSimple command-line tool."
  homepage "https://dnsimple.com"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.5.2/dnsimple_0.5.2_darwin_amd64.tar.gz"
      sha256 "a213b29066a2c1b16556e39102691e908fbf94826d4ac7daf42ce39a88d472bc"

      define_method(:install) do
        bin.install "dnsimple"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.5.2/dnsimple_0.5.2_darwin_arm64.tar.gz"
      sha256 "0f202ae1f74185339f0bad11560f2adf78e54c1b51d0293ea48e5a3abf1614be"

      define_method(:install) do
        bin.install "dnsimple"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.5.2/dnsimple_0.5.2_linux_amd64.tar.gz"
      sha256 "10cc1b83363c2ba983a7cac4b3d2e132c61ee1eb84efd898b550f5b95ceb8b2c"
      define_method(:install) do
        bin.install "dnsimple"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.5.2/dnsimple_0.5.2_linux_arm64.tar.gz"
      sha256 "add0806370a5cebe9ffc0c68defc0a5dbad724d640770e2a8e03b893dc5e308e"
      define_method(:install) do
        bin.install "dnsimple"
      end
    end
  end
end
