# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsimple < Formula
  desc "DNSimple command-line tool."
  homepage "https://dnsimple.com"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.9.0/dnsimple_0.9.0_darwin_amd64.tar.gz"
      sha256 "86284429807e98380788c5892d851306511ba8dec5eef141ade0c3ef97942955"

      define_method(:install) do
        bin.install "dnsimple"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.9.0/dnsimple_0.9.0_darwin_arm64.tar.gz"
      sha256 "a9d8392b554bd6c70c68bb256beb393c081397ab51b6b9086714bf46d41004bb"

      define_method(:install) do
        bin.install "dnsimple"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.9.0/dnsimple_0.9.0_linux_amd64.tar.gz"
      sha256 "1d3b8ab9a2782de8238185c9c0b3efaae73b61a4246ac69f92c90c3fdc59a8d3"
      define_method(:install) do
        bin.install "dnsimple"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnsimple/homebrew-tap/releases/download/v0.9.0/dnsimple_0.9.0_linux_arm64.tar.gz"
      sha256 "5efea42e52e07d83708c300114e69730f066f1f3841f2f06bdca0d494cbb3175"
      define_method(:install) do
        bin.install "dnsimple"
      end
    end
  end
end
